### ISSUE TITLE
Multi-channel CNN for Sentence Classification

### ISSUE THREAD

**Issue by ndrmahmoudi** [shagunsodhani/CNN-Sentence-Classifier#4]
Hi Shagun,

Many thanks for this useful framework of CNN in Keras. I have a very small question about the feeding mutiple word embeddings into CNN. As in the paper, I would like to test how Glove and Word2Vec work together in sentence classification. Can you please let me know how to create embedding layer with multiple word vectors?

Regards,
Nader

**Comment by shagunsodhani** [comment]
Hey @ndrmahmoudi 

The idea is that you create two separate embedding layers - one using Glove and another using Word2Vec and stack them on top of each other to create 2-channel input. This 2 channel view is very similar to the 3 channel (RGB) view for the images. Now you apply convs over this 2 channel view just like you did with the 1 channel view.

I hope this helps.

**Comment by ndrmahmoudi** [comment]
What about the convolution layer? Do I have to have conv2d and MaxPooling2d after that?

**Comment by shagunsodhani** [comment]
yeah :)

**Comment by ndrmahmoudi** [comment]
Thanks Shagun ;)

**Comment by ndrmahmoudi** [comment]
Hi Shagun, I apologize for asking too many questions and thank you for your responses. Now, I have fixed the problem with multiple embeddings + convolutional network. I have two more questions about it and I will appreciate if you response them as well.

1. The model with multi-channel (conv2d) takes much longer and consumes much bigger memory than the model with single channel (conv1d) such that I could not even run one epoch of it. Is this normal? I want to make sure that gpu will solve this issue before changing my system.
  
2. Is it possible to feed multiple word embeddings to recurrent networks like [lstm](https://github.com/fchollet/keras/blob/master/examples/imdb_lstm.py) or even [cnn-lstm](https://github.com/fchollet/keras/blob/master/examples/imdb_cnn_lstm.py) as well? You can see that lstm has been implemented on text classification with single embedding layer. But, when I feed the two-channel embedding layer to lstm it gives the error below:
`ValueError: Input 0 is incompatible with layer lstm_1: expected ndim=3, found ndim=4`
This error is completely logical since my embedding layer has dimension like (batch_size, number of embedding channels, maxlen, embedding dim) which is (None, 2, 30, 300) in my case. I am quite sure that I have to something before adding lstm layer to make dimensions compatible, but what? I could not find same situation around the Internet, so I decided to ask you this question. Can you please help me to this problem too?

Many thanks in advance for your responses.
Nader

**Comment by shagunsodhani** [comment]
Hey @ndrmahmoudi 

1. It is normal for the larger network to take more time and using a GPU would indeed help.
2. You could try pooling the features across different embedding to get a single feature embedding before feeding into the LSTM.

**Comment by ndrmahmoudi** [comment]
Thanks Shagun, 
But, I could understand the idea of pooling. Does't pooling layer return same-size tensor? So, how can I lower the tensor dimension before calling the LSTM layer?

**Comment by shagunsodhani** [comment]
Hey @ndrmahmoudi You can say maxpool or add the embeddings of each word. Please let me know if this does not sound right.
